import type { PrivateCaseRecord } from './types'

export const sampleCases: PrivateCaseRecord[] = [
    {
        id: 'starter-1',
        accessionId: 'OADDL-2026-0001',
        pathogen: 'Trichomoniasis (Tritrichomonas foetus)',
        year: '2026',
        month: '02',
        host: 'Bovine',
        city: 'Faxon',
        state: 'OK',
        zip: '73540',
        county: 'Comanche',
        fips: '40031',
        rawLocation: 'Faxon, OK, 73540',
        result: 'positive',
        testCount: 12,
    },
    {
        id: 'starter-2',
        accessionId: 'OADDL-2025-0002',
        pathogen: 'Trichomoniasis (Tritrichomonas foetus)',
        year: '2025',
        month: '03',
        host: 'Bovine',
        city: 'Blanco',
        state: 'OK',
        zip: '74528',
        county: 'Pittsburg',
        fips: '40121',
        rawLocation: 'Blanco, OK, 74528',
        result: 'positive',
        testCount: 15,
    },
    {
        id: 'starter-3',
        accessionId: 'OADDL-2024-0003',
        pathogen: 'Trichomoniasis (Tritrichomonas foetus)',
        year: '2024',
        month: '01',
        host: 'Bovine',
        city: 'Verden',
        state: 'OK',
        zip: '73092',
        county: 'Grady',
        fips: '40051',
        rawLocation: 'Verden, OK, 73092',
        result: 'positive',
        testCount: 8,
    },
    {
        id: 'starter-4',
        accessionId: 'OADDL-2026-0004',
        pathogen: 'Rabies virus',
        year: '2026',
        month: '02',
        host: 'Wildlife',
        city: 'Stillwater',
        state: 'OK',
        zip: '74074',
        county: 'Payne',
        fips: '40119',
        rawLocation: 'Stillwater, OK, 74074',
        notes: 'Example second pathogen for UI validation.',
        result: 'positive',
        testCount: 4,
    },
]
